//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int id { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public System.DateTime createdDate { get; set; }
    }
}
